### ISSUE TITLE
Add "terraform destroy"

### ISSUE THREAD

**Issue by mfykmn** [mafuyuk/terraform-orb#5]
## Todo
- [x] Fixed plam commands
- [x] Add destroy to commands
- [x] Add destroy to jobs
